name: Build and check fonts

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Install Fontforge
      run: |
        sudo apt remove firefox
        sudo apt update
        sudo apt upgrade
        sudo apt install fontforge
    - name: Build
      run: make
    - name: Make distributable
      run: make dist
    - name: Upload an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ttf
        path: GaramondMono/**
  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get Fontspector configuration file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          fontspector.toml
        sparse-checkout-cone-mode: false
    - name: Install fontspector
      uses: fonttools/setup-fontspector@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download the Artifact
      uses: actions/download-artifact@v4
    - name: Run Fontspector
      run: |
        fontspector --full-lists \
          --configuration fontspector.toml \
          ttf/*.ttf
