name: Build and check fonts

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ">=3.9"
    - name: Build and install Fontforge
      uses: MihailJP/setup-fontforge@v1
    - name: Install Python dependencies
      run: |
        pip3 install "fontforge-ref-sel-util>=0.1.3"
    - name: Build
      run: make
    - name: Make distributable
      run: make dist
    - name: Upload an Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ttf
        path: GaramondMono/**
  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get Fontspector configuration file
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          fontspector.toml
        sparse-checkout-cone-mode: false
    - name: Install fontspector
      uses: fonttools/setup-fontspector@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download the Artifact
      uses: actions/download-artifact@v8
    - name: Run Fontspector
      run: |
        fontspector -l info --full-lists \
          --configuration fontspector.toml \
          *.ttf
